/**
 * notificationEventService.js
 * 
 * Standardized Candidate & Recruiter Notification & Email Event Architecture.
 * 
 * Categorizes internal dashboard notifications and actionable email events.
 * Prepares clean, future-ready payloads ready for backend mailer / SMS API integration
 * without mock persistence or fake email deliveries.
 */

// ─── Candidate Events ────────────────────────────────────────────────────────
export const NOTIFICATION_EVENTS = {
  // Authentication & Security (OTP is handled separately as security message)
  AUTH_REGISTRATION_OTP:        'AUTH_REGISTRATION_OTP',
  AUTH_FORGOT_PASSWORD_OTP:     'AUTH_FORGOT_PASSWORD_OTP',
  AUTH_PASSWORD_CHANGED:        'AUTH_PASSWORD_CHANGED',

  // Job Applications (Direct)
  APP_SUBMITTED:                'APP_SUBMITTED',
  APP_STATUS_CHANGED:           'APP_STATUS_CHANGED',
  APP_SHORTLISTED:              'APP_SHORTLISTED',
  APP_SCREENING:                'APP_SCREENING',
  APP_INTERVIEW_SCHEDULED:      'APP_INTERVIEW_SCHEDULED',
  APP_SELECTED:                 'APP_SELECTED',
  APP_REJECTED:                 'APP_REJECTED',

  // Interviews
  INTERVIEW_SCHEDULED:          'INTERVIEW_SCHEDULED',
  INTERVIEW_RESCHEDULED:        'INTERVIEW_RESCHEDULED',
  INTERVIEW_CANCELLED:          'INTERVIEW_CANCELLED',
  INTERVIEW_REMINDER:           'INTERVIEW_REMINDER',
  INTERVIEW_COMPLETED:          'INTERVIEW_COMPLETED',

  // Job Melas
  JOB_MELA_REGISTERED:          'JOB_MELA_REGISTERED',
  JOB_MELA_REMINDER:            'JOB_MELA_REMINDER',
  JOB_MELA_UPDATED:             'JOB_MELA_UPDATED',
  JOB_MELA_CANCELLED:           'JOB_MELA_CANCELLED',
  JOB_MELA_APP_SUBMITTED:       'JOB_MELA_APP_SUBMITTED',
  JOB_MELA_APP_STATUS_CHANGED:  'JOB_MELA_APP_STATUS_CHANGED',
  JOB_MELA_INTERVIEW_SCHEDULED: 'JOB_MELA_INTERVIEW_SCHEDULED',
  JOB_MELA_SELECTION:           'JOB_MELA_SELECTION',

  // Profile & Account
  PROFILE_COMPLETION_REMINDER:  'PROFILE_COMPLETION_REMINDER',
  RESUME_UPLOADED:              'RESUME_UPLOADED',
  ACCOUNT_SECURITY_ALERT:       'ACCOUNT_SECURITY_ALERT',

  // Support
  SUPPORT_TICKET_CREATED:       'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_REPLY:         'SUPPORT_TICKET_REPLY',
  SUPPORT_TICKET_RESOLVED:      'SUPPORT_TICKET_RESOLVED',
};

// ─── Recruiter Events ────────────────────────────────────────────────────────
export const RECRUITER_NOTIFICATION_EVENTS = {
  // Applications
  RECRUITER_APP_RECEIVED:              'RECRUITER_APP_RECEIVED',
  RECRUITER_JOB_MELA_APP_RECEIVED:     'RECRUITER_JOB_MELA_APP_RECEIVED',
  RECRUITER_CANDIDATE_SHORTLISTED:     'RECRUITER_CANDIDATE_SHORTLISTED',
  RECRUITER_INTERVIEW_SCHEDULED:       'RECRUITER_INTERVIEW_SCHEDULED',
  RECRUITER_INTERVIEW_RESCHEDULED:     'RECRUITER_INTERVIEW_RESCHEDULED',
  RECRUITER_INTERVIEW_CANCELLED:       'RECRUITER_INTERVIEW_CANCELLED',
  RECRUITER_INTERVIEW_COMPLETED:       'RECRUITER_INTERVIEW_COMPLETED',
  RECRUITER_CANDIDATE_SELECTED:        'RECRUITER_CANDIDATE_SELECTED',
  RECRUITER_CANDIDATE_REJECTED:        'RECRUITER_CANDIDATE_REJECTED',

  // Jobs
  RECRUITER_JOB_SUBMITTED:             'RECRUITER_JOB_SUBMITTED',
  RECRUITER_JOB_APPROVED:              'RECRUITER_JOB_APPROVED',
  RECRUITER_JOB_REJECTED:              'RECRUITER_JOB_REJECTED',
  RECRUITER_JOB_PUBLISHED:             'RECRUITER_JOB_PUBLISHED',
  RECRUITER_JOB_CLOSED:                'RECRUITER_JOB_CLOSED',
  RECRUITER_JOB_EXPIRED:               'RECRUITER_JOB_EXPIRED',
  RECRUITER_JOB_CORRECTION_REQUIRED:   'RECRUITER_JOB_CORRECTION_REQUIRED',

  // Internships
  RECRUITER_INTERNSHIP_SUBMITTED:      'RECRUITER_INTERNSHIP_SUBMITTED',
  RECRUITER_INTERNSHIP_APPROVED:       'RECRUITER_INTERNSHIP_APPROVED',
  RECRUITER_INTERNSHIP_REJECTED:       'RECRUITER_INTERNSHIP_REJECTED',
  RECRUITER_INTERNSHIP_PUBLISHED:      'RECRUITER_INTERNSHIP_PUBLISHED',
  RECRUITER_INTERNSHIP_CLOSED:         'RECRUITER_INTERNSHIP_CLOSED',
  RECRUITER_INTERNSHIP_EXPIRED:        'RECRUITER_INTERNSHIP_EXPIRED',

  // Verification
  RECRUITER_VERIFICATION_APPROVED:         'RECRUITER_VERIFICATION_APPROVED',
  RECRUITER_VERIFICATION_REJECTED:         'RECRUITER_VERIFICATION_REJECTED',
  RECRUITER_COMPANY_VERIFICATION_APPROVED: 'RECRUITER_COMPANY_VERIFICATION_APPROVED',
  RECRUITER_COMPANY_VERIFICATION_REJECTED: 'RECRUITER_COMPANY_VERIFICATION_REJECTED',
  RECRUITER_VERIFICATION_DOCS_REQUIRED:    'RECRUITER_VERIFICATION_DOCS_REQUIRED',

  // Interviews
  RECRUITER_INTERVIEW_REMINDER:            'RECRUITER_INTERVIEW_REMINDER',
  RECRUITER_INTERVIEW_FEEDBACK_REQUIRED:   'RECRUITER_INTERVIEW_FEEDBACK_REQUIRED',

  // Job Melas
  RECRUITER_JOB_MELA_REQUEST_SUBMITTED:    'RECRUITER_JOB_MELA_REQUEST_SUBMITTED',
  RECRUITER_JOB_MELA_REQUEST_APPROVED:     'RECRUITER_JOB_MELA_REQUEST_APPROVED',
  RECRUITER_JOB_MELA_REQUEST_REJECTED:     'RECRUITER_JOB_MELA_REQUEST_REJECTED',
  RECRUITER_JOB_MELA_UPDATED:              'RECRUITER_JOB_MELA_UPDATED',
  RECRUITER_JOB_MELA_CANCELLED:            'RECRUITER_JOB_MELA_CANCELLED',

  // Hiring Team
  RECRUITER_TEAM_MEMBER_ADDED:             'RECRUITER_TEAM_MEMBER_ADDED',
  RECRUITER_TEAM_INVITATION_ACCEPTED:      'RECRUITER_TEAM_INVITATION_ACCEPTED',
  RECRUITER_TEAM_INVITATION_DECLINED:      'RECRUITER_TEAM_INVITATION_DECLINED',
  RECRUITER_TEAM_MEMBER_REMOVED:           'RECRUITER_TEAM_MEMBER_REMOVED',

  // Support & Security
  RECRUITER_SUPPORT_TICKET_CREATED:        'RECRUITER_SUPPORT_TICKET_CREATED',
  RECRUITER_SUPPORT_TICKET_REPLY:          'RECRUITER_SUPPORT_TICKET_REPLY',
  RECRUITER_SUPPORT_TICKET_RESOLVED:       'RECRUITER_SUPPORT_TICKET_RESOLVED',
  RECRUITER_PASSWORD_CHANGED:              'RECRUITER_PASSWORD_CHANGED',
  RECRUITER_SECURITY_ALERT:                'RECRUITER_SECURITY_ALERT',
};

/**
 * Candidate events that trigger email dispatch
 */
export const EMAIL_TRIGGERED_EVENTS = new Set([
  NOTIFICATION_EVENTS.AUTH_REGISTRATION_OTP,
  NOTIFICATION_EVENTS.AUTH_FORGOT_PASSWORD_OTP,
  NOTIFICATION_EVENTS.AUTH_PASSWORD_CHANGED,
  NOTIFICATION_EVENTS.APP_SUBMITTED,
  NOTIFICATION_EVENTS.APP_SHORTLISTED,
  NOTIFICATION_EVENTS.APP_STATUS_CHANGED,
  NOTIFICATION_EVENTS.APP_INTERVIEW_SCHEDULED,
  NOTIFICATION_EVENTS.APP_SELECTED,
  NOTIFICATION_EVENTS.APP_REJECTED,
  NOTIFICATION_EVENTS.INTERVIEW_SCHEDULED,
  NOTIFICATION_EVENTS.INTERVIEW_RESCHEDULED,
  NOTIFICATION_EVENTS.INTERVIEW_CANCELLED,
  NOTIFICATION_EVENTS.INTERVIEW_REMINDER,
  NOTIFICATION_EVENTS.JOB_MELA_REGISTERED,
  NOTIFICATION_EVENTS.JOB_MELA_REMINDER,
  NOTIFICATION_EVENTS.JOB_MELA_APP_SUBMITTED,
  NOTIFICATION_EVENTS.JOB_MELA_APP_STATUS_CHANGED,
  NOTIFICATION_EVENTS.JOB_MELA_INTERVIEW_SCHEDULED,
  NOTIFICATION_EVENTS.JOB_MELA_SELECTION,
  NOTIFICATION_EVENTS.SUPPORT_TICKET_CREATED,
  NOTIFICATION_EVENTS.SUPPORT_TICKET_REPLY,
  NOTIFICATION_EVENTS.SUPPORT_TICKET_RESOLVED,
]);

/**
 * Recruiter events that trigger email dispatch
 */
export const RECRUITER_EMAIL_TRIGGERED_EVENTS = new Set([
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_APP_RECEIVED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_JOB_MELA_APP_RECEIVED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_INTERVIEW_SCHEDULED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_INTERVIEW_RESCHEDULED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_INTERVIEW_CANCELLED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_INTERVIEW_REMINDER,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_JOB_APPROVED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_JOB_REJECTED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_INTERNSHIP_APPROVED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_INTERNSHIP_REJECTED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_VERIFICATION_APPROVED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_VERIFICATION_REJECTED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_COMPANY_VERIFICATION_APPROVED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_COMPANY_VERIFICATION_REJECTED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_JOB_MELA_REQUEST_APPROVED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_JOB_MELA_REQUEST_REJECTED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_SUPPORT_TICKET_REPLY,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_SUPPORT_TICKET_RESOLVED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_PASSWORD_CHANGED,
  RECRUITER_NOTIFICATION_EVENTS.RECRUITER_SECURITY_ALERT,
]);

/**
 * Dispatches a Candidate Notification Event.
 */
export function dispatchCandidateEvent({
  eventType,
  candidateEmail,
  recipientName = 'Candidate',
  notification,
  addNotification,
  meta = {},
}) {
  const isEmailActionable = EMAIL_TRIGGERED_EVENTS.has(eventType);

  // 1. Trigger internal notification if provided and handler passed
  if (notification && typeof addNotification === 'function') {
    addNotification('candidate', {
      ...notification,
      meta: {
        ...meta,
        ...(notification.meta || {}),
        eventType,
      }
    });
  }

  // 2. Prepare structured email payload ready for backend API integration
  const emailPayload = isEmailActionable ? {
    to: candidateEmail,
    recipientName,
    eventType,
    subject: notification?.title || `NTR VIKASA Notification: ${eventType}`,
    templateData: {
      ...meta,
      message: notification?.message || '',
      date: new Date().toISOString(),
    },
    dispatchedAt: new Date().toISOString(),
  } : null;

  return {
    success: true,
    eventType,
    isEmailActionable,
    emailPayload,
  };
}

/**
 * Dispatches a Recruiter Notification Event.
 */
export function dispatchRecruiterEvent({
  eventType,
  recruiterEmail,
  recipientName = 'Recruiter',
  notification,
  addNotification,
  meta = {},
}) {
  const isEmailActionable = RECRUITER_EMAIL_TRIGGERED_EVENTS.has(eventType);

  // 1. Trigger internal notification if provided and handler passed
  if (notification && typeof addNotification === 'function') {
    addNotification('recruiter', {
      ...notification,
      meta: {
        ...meta,
        ...(notification.meta || {}),
        eventType,
      }
    });
  }

  // 2. Prepare structured email payload ready for backend API integration
  const emailPayload = isEmailActionable ? {
    to: recruiterEmail,
    recipientName,
    eventType,
    subject: notification?.title || `NTR VIKASA Recruiter Alert: ${eventType}`,
    templateData: {
      ...meta,
      message: notification?.message || '',
      date: new Date().toISOString(),
    },
    dispatchedAt: new Date().toISOString(),
  } : null;

  return {
    success: true,
    eventType,
    isEmailActionable,
    emailPayload,
  };
}

// ─── Admin Events ────────────────────────────────────────────────────────────
export const ADMIN_NOTIFICATION_EVENTS = {
  // Recruiters & Companies
  ADMIN_RECRUITER_REGISTRATION:            'ADMIN_RECRUITER_REGISTRATION',
  ADMIN_RECRUITER_VERIFICATION_PENDING:    'ADMIN_RECRUITER_VERIFICATION_PENDING',
  ADMIN_RECRUITER_DOCS_SUBMITTED:          'ADMIN_RECRUITER_DOCS_SUBMITTED',
  ADMIN_RECRUITER_VERIFICATION_REQUIRED:   'ADMIN_RECRUITER_VERIFICATION_REQUIRED',
  ADMIN_RECRUITER_VERIFIED:                'ADMIN_RECRUITER_VERIFIED',
  ADMIN_RECRUITER_REJECTED:                'ADMIN_RECRUITER_REJECTED',
  ADMIN_COMPANY_REGISTRATION:              'ADMIN_COMPANY_REGISTRATION',
  ADMIN_COMPANY_VERIFICATION_PENDING:      'ADMIN_COMPANY_VERIFICATION_PENDING',
  ADMIN_COMPANY_DOCS_SUBMITTED:            'ADMIN_COMPANY_DOCS_SUBMITTED',
  ADMIN_COMPANY_VERIFICATION_REQUIRED:     'ADMIN_COMPANY_VERIFICATION_REQUIRED',
  ADMIN_COMPANY_APPROVED:                  'ADMIN_COMPANY_APPROVED',
  ADMIN_COMPANY_REJECTED:                  'ADMIN_COMPANY_REJECTED',

  // Job Approvals
  ADMIN_JOB_SUBMITTED:                     'ADMIN_JOB_SUBMITTED',
  ADMIN_JOB_RESUBMITTED:                   'ADMIN_JOB_RESUBMITTED',
  ADMIN_JOB_REVIEW_REQUIRED:               'ADMIN_JOB_REVIEW_REQUIRED',
  ADMIN_JOB_MODERATION_PENDING:            'ADMIN_JOB_MODERATION_PENDING',
  ADMIN_JOB_APPROVED:                      'ADMIN_JOB_APPROVED',
  ADMIN_JOB_REJECTED:                      'ADMIN_JOB_REJECTED',

  // Internship Approvals
  ADMIN_INTERNSHIP_SUBMITTED:              'ADMIN_INTERNSHIP_SUBMITTED',
  ADMIN_INTERNSHIP_RESUBMITTED:            'ADMIN_INTERNSHIP_RESUBMITTED',
  ADMIN_INTERNSHIP_REVIEW_REQUIRED:        'ADMIN_INTERNSHIP_REVIEW_REQUIRED',
  ADMIN_INTERNSHIP_MODERATION_PENDING:     'ADMIN_INTERNSHIP_MODERATION_PENDING',
  ADMIN_INTERNSHIP_APPROVED:               'ADMIN_INTERNSHIP_APPROVED',
  ADMIN_INTERNSHIP_REJECTED:               'ADMIN_INTERNSHIP_REJECTED',

  // Job Melas
  ADMIN_JOB_MELA_REQUEST_SUBMITTED:        'ADMIN_JOB_MELA_REQUEST_SUBMITTED',
  ADMIN_JOB_MELA_REQUEST_UPDATED:          'ADMIN_JOB_MELA_REQUEST_UPDATED',
  ADMIN_JOB_MELA_REVIEW_REQUIRED:          'ADMIN_JOB_MELA_REVIEW_REQUIRED',
  ADMIN_JOB_MELA_CANCELLATION_ACTION:      'ADMIN_JOB_MELA_CANCELLATION_ACTION',
  ADMIN_JOB_MELA_PARTICIPATION_REVIEW:     'ADMIN_JOB_MELA_PARTICIPATION_REVIEW',
  ADMIN_JOB_MELA_APPROVED:                 'ADMIN_JOB_MELA_APPROVED',
  ADMIN_JOB_MELA_REJECTED:                 'ADMIN_JOB_MELA_REJECTED',

  // Reports & Complaints
  ADMIN_REPORT_SUBMITTED:                  'ADMIN_REPORT_SUBMITTED',
  ADMIN_COMPLAINT_SUBMITTED:               'ADMIN_COMPLAINT_SUBMITTED',
  ADMIN_HIGH_PRIORITY_COMPLAINT:           'ADMIN_HIGH_PRIORITY_COMPLAINT',
  ADMIN_REPORT_ACTION_REQUIRED:            'ADMIN_REPORT_ACTION_REQUIRED',
  ADMIN_COMPLAINT_ESCALATED:               'ADMIN_COMPLAINT_ESCALATED',
  ADMIN_REPORT_RESOLVED:                   'ADMIN_REPORT_RESOLVED',

  // Support
  ADMIN_CANDIDATE_TICKET_CREATED:          'ADMIN_CANDIDATE_TICKET_CREATED',
  ADMIN_RECRUITER_TICKET_CREATED:          'ADMIN_RECRUITER_TICKET_CREATED',
  ADMIN_SUPPORT_TICKET_ESCALATED:          'ADMIN_SUPPORT_TICKET_ESCALATED',
  ADMIN_SUPPORT_ACTION_REQUIRED:           'ADMIN_SUPPORT_ACTION_REQUIRED',

  // Security & Platform
  ADMIN_SECURITY_ACCESS_CHANGED:           'ADMIN_SECURITY_ACCESS_CHANGED',
  ADMIN_SECURITY_ALERT:                    'ADMIN_SECURITY_ALERT',
  ADMIN_MAINTENANCE_SCHEDULED:             'ADMIN_MAINTENANCE_SCHEDULED',
  ADMIN_MAINTENANCE_COMPLETED:             'ADMIN_MAINTENANCE_COMPLETED',
  ADMIN_PASSWORD_CHANGED:                  'ADMIN_PASSWORD_CHANGED',
};

/**
 * Admin events that trigger email dispatch (strictly important actionable events)
 */
export const ADMIN_EMAIL_TRIGGERED_EVENTS = new Set([
  ADMIN_NOTIFICATION_EVENTS.ADMIN_RECRUITER_VERIFICATION_PENDING,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_RECRUITER_VERIFICATION_REQUIRED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_COMPANY_VERIFICATION_PENDING,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_COMPANY_VERIFICATION_REQUIRED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_JOB_SUBMITTED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_JOB_REVIEW_REQUIRED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_JOB_MODERATION_PENDING,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_INTERNSHIP_SUBMITTED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_INTERNSHIP_REVIEW_REQUIRED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_JOB_MELA_REQUEST_SUBMITTED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_JOB_MELA_REVIEW_REQUIRED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_JOB_MELA_PARTICIPATION_REVIEW,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_REPORT_SUBMITTED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_COMPLAINT_SUBMITTED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_HIGH_PRIORITY_COMPLAINT,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_REPORT_ACTION_REQUIRED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_COMPLAINT_ESCALATED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_CANDIDATE_TICKET_CREATED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_RECRUITER_TICKET_CREATED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_SUPPORT_TICKET_ESCALATED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_SUPPORT_ACTION_REQUIRED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_SECURITY_ALERT,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_SECURITY_ACCESS_CHANGED,
  ADMIN_NOTIFICATION_EVENTS.ADMIN_PASSWORD_CHANGED,
]);

/**
 * Dispatches an Admin Notification Event.
 */
export function dispatchAdminEvent({
  eventType,
  adminEmail = 'admin1@ntrvikasa.com',
  recipientName = 'Platform Administrator',
  notification,
  addNotification,
  meta = {},
}) {
  const isEmailActionable = ADMIN_EMAIL_TRIGGERED_EVENTS.has(eventType);

  // 1. Trigger internal notification if provided and handler passed
  if (notification && typeof addNotification === 'function') {
    addNotification('admin', {
      ...notification,
      meta: {
        ...meta,
        ...(notification.meta || {}),
        eventType,
      }
    });
  }

  // 2. Prepare structured email payload ready for backend API integration
  const emailPayload = isEmailActionable ? {
    to: adminEmail,
    recipientName,
    eventType,
    subject: notification?.title || `NTR VIKASA Admin Action Alert: ${eventType}`,
    templateData: {
      ...meta,
      message: notification?.message || '',
      date: new Date().toISOString(),
    },
    dispatchedAt: new Date().toISOString(),
  } : null;

  return {
    success: true,
    eventType,
    isEmailActionable,
    emailPayload,
  };
}

